spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./aoc
    username: aoc
    password: aoc

  sql:
    init:
      mode: always
      schema-locations: classpath:db.sql

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com:
      xin: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true
